- chk/constants/archetype/validation.py
- tests/archetypes/defaults/http_config_test.py
- tests/resources/storage/sample_config/fail_cases/GET-WithBasicAuth-AsList.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithBasicAuth-Empty.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithBearerAuth-AsList.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithBearerAuth-Empty.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithHeaders-AsList.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithHeaders-Empty.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithQuery-AsList.chk
- tests/resources/storage/sample_config/fail_cases/GET-WithQuery-Empty.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyForm-AsList.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyForm-Empty.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyFormData-AsList.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyFormData-Empty.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyJson-Empty.chk
- tests/resources/storage/sample_config/fail_cases/POST-WithBodyXML-Empty.chk
- tests/resources/storage/sample_config/pass_cases/GET-Plain.chk
- tests/resources/storage/sample_config/pass_cases/GET-WithBasicAuth.chk
- tests/resources/storage/sample_config/pass_cases/GET-WithBearerAuth.chk
- tests/resources/storage/sample_config/pass_cases/GET-WithHeaders.chk
- tests/resources/storage/sample_config/pass_cases/GET-WithQuery.chk
- tests/resources/storage/sample_config/pass_cases/POST-Plain.chk
- tests/resources/storage/sample_config/pass_cases/POST-WithBodyForm.chk
- tests/resources/storage/sample_config/pass_cases/POST-WithBodyFormData.chk
- tests/resources/storage/sample_config/pass_cases/POST-WithBodyJson.chk
- tests/resources/storage/sample_config/pass_cases/POST-WithBodyJson2.chk
- tests/resources/storage/sample_config/pass_cases/POST-WithBodyXML.chk
> Feature: validations and tests for request items

- chk/support/http_requestor.py
- chk/support/output_cli.py
- tests/resources/storage/sample_config/pass_cases/HEAD-WithBodyJson2.chk
- tests/resources/storage/sample_config/pass_cases/OPTIONS-WithBodyJson2.chk
> feature: allow HEAD and OPTIONS methods to send request body with test

- chk/constants/archetype/rules.py
- chk/constants/archetype/validation.py
- tests/archetypes/defaults/http_config_test.py
> feature: only listed http method allowed with test

- chk/constants/archetype/rules.py
- chk/constants/archetype/validation.py
- tests/archetypes/defaults/http_config_test.py
> feature: only url with http and https schemes are allowed with test

- chk/__init__.py
- docs/CONTRIBUTING.md
- setup.cfg
- remove version from chk module
- update docs for help string
Closes: #28
> feature: platform support for windows

- setup.cfg
- add more keyword for pypi indexing
- update chk entrypoint
Closes: #27
> feature: linux plaform support

- chk/modules/http/validation_rules.py
- tests/modules/http/http_entities_test.py
- tests/resources/storage/sample_config/fail_cases/POST-WithManyBody.chk
> feature: Allow only one body type in http file

- chk/modules/http/request_helper.py
> hotfix: nested dict data not getting sent in body[json]

- chk/modules/http/constants.py
- chk/modules/http/entities.py
- chk/modules/http/main.py
- chk/modules/http/presentation.py
- chk/modules/http/request_helper.py
- chk/modules/http/support.py
- chk/modules/http/validation_rules.py
- chk/modules/variables/support.py
- tests/resources/storage/sample_config/pass_cases/PUT-Return-Var.chk
> Feature: support `return` statement in `http.request` block

- chk/modules/http/validation_rules.py
> Improvement: docstring updated for the funcion allowed_url. #104

- chk/modules/variables/lexicon.py
> refactor: improve replace_in_str impl

- chk/modules/variables/lexicon.py
Fixed issue with test case failing
> fix: allow one or more of word

- setup.cfg
> Latest dependencies updated in setup.cfg

- docs/release-build.md
closes #96 
[See here](https://github.com/0hsn/chkware-cli/blob/f5f1ba9726ef7ac50ba2a03d07b68d4794dc4ce8/docs/release-build.md)
> docs: release build process

- .github/workflows/macos-ci-test.yml
> ci tests on macOS

- .github/workflows/linux-run-tests.yml
- .github/workflows/test-linux.yml
> Feature: Github action to run tests on Linux

- .github/workflows/windows-run-tests.yml
> windows ci tests

- chk/infrastructure/containers.py
- chk/modules/http/entities.py
- chk/modules/http/presentation.py
- chk/modules/variables/support.py
- tests/infrastructure/app_container_test.py
- tests/modules/http/http_entities_test.py
- tests/modules/http/http_presentation_test.py
- tests/modules/variables/support_test.py
> Fix: pytest issues

- chk/infrastructure/translation.py
- chk/modules/http/entities.py
- chk/modules/testcase/entities.py
- chk/modules/testcase/support.py
- chk/modules/variables/support.py
- chk/modules/version/support.py
- tests/modules/version/version_support_test.py
- tests/resources/storage/sample_config/UserCommentedVersion.chk
- tests/resources/storage/sample_config/UserNoVersion.chk
> Refactor: http module v1

- Pipfile.lock
- chk/infrastructure/containers.py
- chk/infrastructure/exception.py
- chk/modules/http/constants.py
- chk/modules/http/entities.py
- chk/modules/http/presentation.py
- chk/modules/http/request_helper.py
- chk/modules/http/support.py
- chk/modules/variables/constants.py
- chk/modules/variables/entities.py
- chk/modules/variables/lexicon.py
- chk/modules/variables/support.py
- chk/modules/variables/validation_rules.py
- chk/modules/version/constants.py
- requirements.txt
- tests/infrastructure/app_container_test.py
- tests/modules/http/http_entities_test.py
- tests/modules/variables/string_lexical_analyzer_test.py
- tests/modules/variables/support_test.py
- tests/resources/storage/sample_config/UserOk.chk
> Feature: http expose statement

- chk/console/main.py
- chk/infrastructure/file_loader.py
- chk/modules/http/main.py
- chk/modules/testcase/constants.py
- chk/modules/testcase/entities.py
- chk/modules/testcase/main.py
- chk/modules/testcase/support/execute.py
- chk/modules/testcase/validation_rules.py
- chk/modules/variables/lexicon.py
- chk/modules/variables/support.py
- tests/infrastructure/file_loader_test.py
- tests/modules/http/http_entities_test.py
- tests/modules/http/http_main_test.py
- tests/modules/testcase/support_execute_test.py
- tests/modules/variables/string_lexical_analyzer_test.py
- tests/modules/variables/variables_support_test.py
- tests/resources/storage/sample_config/fail_cases/GET-Plain-WrongURL.chk
- tests/resources/storage/sample_config/pass_cases/testcases/01_UserCreateSpecPassVars.chk
- tests/resources/storage/sample_config/pass_cases/testcases/02_POST-SpecWithRequest.chk
- tests/resources/storage/sample_config/pass_cases/testcases/02_POST-SpecWithRequestAndSpecFull.chk
- tests/resources/storage/sample_config/pass_cases/testcases/02_POST-SpecWithRequestAndSpecFullVar.chk
- tests/resources/storage/sample_config/pass_cases/testcases/03_UserCreateRequest_ResList.chk
- tests/resources/storage/sample_config/pass_cases/testcases/03_UserCreateSpec_ResultList.chk
- tests/resources/storage/sample_config/pass_cases/testcases/03_UserCreateSpec_ResultListIgnore.chk
- tests/resources/storage/sample_config/pass_cases/testcases/04_UserCreateSpec_NoResult.chk
> Feat: Test case out-file request execution

- chk/console/main.py
- chk/infrastructure/containers.py
- chk/infrastructure/file_loader.py
- chk/modules/http/main.py
- chk/modules/testcase/entities.py
- chk/modules/testcase/main.py
- chk/modules/testcase/support/execute.py
- chk/modules/variables/support.py
- tests/infrastructure/app_container_test.py
- tests/infrastructure/file_loader_test.py
- tests/modules/assertion/assertion_support_test.py
- tests/modules/http/http_main_test.py
- tests/modules/http/http_request_helper_test.py
- tests/modules/http/http_validation_rules_test.py
- tests/modules/testcase/support_assertion_test.py
- tests/modules/testcase/support_execute_test.py
- tests/modules/testcase/support_testcase_test.py
- tests/modules/variables/variables_support_test.py
- tests/resources/storage/sample_config/pass_cases/testcases/03_UserCreateRequest_ResListWithBody.chk
- tests/resources/storage/sample_config/pass_cases/variables/UserCreateSpec_PassVar.chk
> Feature: Pass values from callee using with statement

- chk/console/main.py
- chk/infrastructure/containers.py
- chk/modules/http/main.py
- chk/modules/testcase/main.py
- chk/modules/testcase/presentation.py
- chk/modules/testcase/support/assertion/support.py
> Feat: `--no-format`. `-nf` command-line flag for both http  and testcase

- chk/console/main.py
- tests/resources/storage/sample_config/xkcd-joke-test.chk
> feat: Add support for variable pass from CLI context for testcase

- chk/console/main.py
- chk/infrastructure/containers.py
- chk/infrastructure/file_loader.py
- chk/infrastructure/helper.py
- chk/infrastructure/work.py
- chk/modules/http/request_helper.py
- chk/modules/testcase/support/execute.py
- chk/modules/variables/entities.py
- chk/modules/version/constants.py
- chk/modules/version/support.py
- tests/modules/http/http_request_helper_test.py
- tests/modules/version/version_support_test.py
> refactor: remove unused interface RequestProcessorContract

- tests/infrastructure/app_container_test.py
- tests/infrastructure/file_loader_test.py
- tests/modules/http/http_entities_test.py
- tests/modules/http/http_main_test.py
- tests/modules/testcase/support_assertion_test.py
- tests/modules/testcase/support_execute_test.py
- tests/modules/testcase/support_testcase_test.py
- tests/modules/version/version_support_test.py
- tests/resources/storage/sample_flow/python/bitcoin-usd.chk
- tests/resources/storage/sample_flow/python/bitcoin_sample_01.py
- tests/resources/storage/sample_flow/python/chucknorris_io/get_random_jokes_for_category.py
- tests/resources/storage/sample_flow/python/chucknorris_io/joke_categories_rq.chk
- tests/resources/storage/sample_flow/python/chucknorris_io/joke_for_category_rq.chk
- tests/resources/storage/sample_flow/python/pokeapi_co/Berries.chk
- tests/resources/storage/sample_flow/python/pokeapi_co/Berry.chk
- tests/resources/storage/sample_flow/python/pokeapi_co/check_berries.py
> feat: same flow in python

- chk/modules/testcase/support/execute.py
- tests/modules/testcase/support_execute_test.py
> Fix: Expose vars missing

- chk/__main__.py
- chk/console/main.py
- chk/infrastructure/file_loader.py
> Feature: Convert commad-line variables arguments (#221)

- chk/infrastructure/third_party/http_fetcher.py
- chk/modules/fetch.py
- tests/infrastructure/symbol_table_test.py
- tests/modules/fetch/fetch_request_helper_test.py
- tests/resources/storage/spec_docs/fetch/httpbin-auth-ba.chk
- tests/resources/storage/spec_docs/fetch/httpbin-auth-be.chk
- tests/resources/storage/spec_docs/fetch/httpbin-form.chk
- tests/resources/storage/spec_docs/fetch/httpbin-formdata.chk
- tests/resources/storage/spec_docs/fetch/httpbin-json.chk
- tests/resources/storage/spec_docs/fetch/httpbin-text.chk
- tests/resources/storage/spec_docs/fetch/httpbin-xml.chk
> Feature: Tag support for fetch module

- tests/infrastructure/templating_test.py
- tests/modules/fetch/fetch_request_helper_test.py
Quality issues raised at SonarCLoud are fixed now
> fix: unreachable asserts while testing exception raise

- .github/workflows/coverage-ci.yaml
- chk/console/main.py
> Fix: Broken CI fix - Coverage report broken

- chk/console/main.py
- chk/console/services.py
> feat: read input data from piped input for validate

- chk/infrastructure/symbol_table.py
- chk/infrastructure/templating.py
- chk/modules/validate/assertion_services.py
- chk/modules/workflow/__init__.py
> Bug Fix: Attribute error on Workflow module

- chk/console/main.py
- poetry.lock
- requirements-dev.txt
- requirements.txt
> Feature: Setup semantic release
